module.exports = {
  'OK' : 200,
  'INVALID' : 400,
  'INVALID_M': 'Invalid entries. Try again.',
  'CREATED' : 201,
  'UNAUTHORIZED' : 401,
  'NOTFOUND' : 404,
  'ERRO' : 500,
  'NOTUNIQUE': 409,
  'NOTUNIQUE_M': 'Email already registered.',
  'FILLFIELDS': 401,
  'FILLFIELDS_M': 'All fields must be filled',
  'INCORRECT': 401,
  'INCORRECT_M': 'Incorrect username or password',
};
